import type { Metadata } from "next";
import { Josefin_Sans as JosefinSans } from "next/font/google";
import "./globals.css";
import RootLayout2 from "@/components/layout2";

const josefinSans = JosefinSans({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "T-Trana",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={josefinSans.className}>
        <RootLayout2>{children}</RootLayout2>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Josefin_Sans as JosefinSans } from "next/font/google";
// import "./globals.css";
// import RootLayout2 from "./components/layout2";

// const josefinSans = JosefinSans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "T-Trana",
//   description: "Generated by create next app",
// };

// export default function Layout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={josefinSans.className}>
//         <RootLayout2> {children} </RootLayout2>
//       </body>
//     </html>
//   );
// }
